### ISSUE TITLE
CreateContext test does not check the min resolution

### ISSUE THREAD

**Issue by XinfengZhang** [01org/libva-utils#83]
in TEST_P(VAAPICreateContext, CreateContext)
only max-resolution is checked.

**Comment by uartie** [comment]
@XinfengZhang can you specify the specific test cases that fail?

**Comment by uartie** [comment]
I see several of them fail due to iHD driver not returning any surface attributes for min/max width/height (e.g. VAProfileVC1Advanced:VAEntrypointVLD).

**Comment by uartie** [comment]
@XinfengZhang For iHD driver, min/max width/height attributes are only returned for VAEntrypointVideoProc and all those test cases pass.  The other tests fail because the driver does not return min/max attributes.

I agree, though, that the test should check min resolution too... but this is not the cause for the failures since driver doesn't even return those attribs.  Please fix the driver to provide those attribs.

**Comment by uartie** [comment]
On the flip-side, I suppose if driver does not specify VASurfaceAttribMaxWidth/Height or VASurfaceAttribMinWidth/Height then applications should assume "any" max is allowed and 0 (or 1) is minimum?  @xhaihao what's your recommendation?

**Comment by xhaihao** [comment]
I prefer '1' as the minimum if the driver doesn't set VASurfaceAttribMinWidth/Height. I agree 'any' max should be allowed if the driver doesn't specify VASurfaceAttribMaxWidth/Height.

**Comment by XinfengZhang** [comment]
@uartie, there are several PR in the https://github.com/intel/media-driver/pulls, Max/Min solution is added for both Decode & Encode, after them, there are still failed. I checked the failed case , and find , if driver report min resolution is 32x32, but our test still expect success with resolution 16x16.

**Comment by uartie** [comment]
@XinfengZhang I will submit a patch to fix that here.
